# Dependencies
markdown:         redcarpet
highligher:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Git @ Me
tagline:          'Discover great open source projects every week'
description:      'Open source solutions'
url:              http://gitat.me
baseurl:          /

author:
  name:           'Neal Shyam'
  url:            https://twitter.com/nealrs

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nealrs/gitatme-comments/

demo:             http://gam.s3.amazonaws.com/demo/
img:              http://gam.s3.amazonaws.com/img/
aws:              http://gam.s3.amazonaws.com/

timezone:         America/New_York
TZ:               America/New_York
